# Copyright 2023 NXROBO
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import List, Optional, Text, Union

from launch import LaunchContext, SomeSubstitutionsType
from launch.actions import DeclareLaunchArgument
from launch.substitutions import (
    Command,
    EnvironmentVariable,
    FindExecutable,
    LaunchConfiguration,
    PathJoinSubstitution,
    TextSubstitution,
)
from launch_ros.substitutions import FindPackageShare



class DeclareSagittariusArmDescriptionLaunchArgument(DeclareLaunchArgument):
    """Generate a URDF of an Arm through a modified DeclareLaunchArgument object."""

    def __init__(
        self,
        *,
        default_value: Optional[SomeSubstitutionsType] = Command([
            FindExecutable(name='xacro'), ' ',
            PathJoinSubstitution([
                FindPackageShare('sagittarius_descriptions'),
                'urdf',
                LaunchConfiguration('robot_model')
            ]), '.urdf.xacro ',
            'robot_name:=', LaunchConfiguration('robot_name'), ' ',
            # 'robot_model:=', 'sgr532_master', ' ',
            'load_gazebo_configs:=', LaunchConfiguration('load_gazebo_configs'), ' ',
            'use_world_frame:=', LaunchConfiguration('use_world_frame'), ' ',
            'external_urdf_loc:=', LaunchConfiguration('external_urdf_loc'), ' ',
            'device_type:=', LaunchConfiguration('device_type'), ' ',

        ]), 
        **kwargs
    ) -> None:
        """
        Construct the modified DeclareLaunchArgument object.

        :param default_value: The default model given to the parent DeclareLaunchArgument; if you
            want to override this value, it must follow the convention in this object's source
        """
        super().__init__(
            name='robot_description',
            default_value=default_value,
            description=(
                'URDF of the robot; this is typically generated by the xacro command.'
            ),
            choices=None,
            **kwargs
        )



def construct_sagittarius_arm_semantic_robot_description_command(
    robot_model: str,
    config_path: Union[PathJoinSubstitution, str],
) -> Command:
    """
    Construct the Arm semantic robot description required by MoveIt.

    :param robot_model: The performed robot_model LaunchConfiguration
    :param config_path: The absolute path to the parent directory of the directory containing the
        srdf
    :return: A launch.substitutions.Command containing info to build the srdf

    :details: The LaunchConfigurations used in this method must already have been declared. This
        can be done by using the declare_sagittarius_arm_robot_description_launch_arguments method
        to declare the robot_description launch args.
    """
    return Command([
        PathJoinSubstitution([
            FindExecutable(name='xacro')
        ]),
        ' ',
        config_path,
        f'/srdf/{robot_model}.srdf.xacro', ' ',
        'robot_name:=', LaunchConfiguration('robot_name'), ' ',
        # 'robot_model:=', LaunchConfiguration('robot_model'), ' ',
        'load_gazebo_configs:=', LaunchConfiguration('load_gazebo_configs'), ' ',
        'use_world_frame:=', LaunchConfiguration('use_world_frame'), ' ',
        'external_urdf_loc:=', LaunchConfiguration('external_urdf_loc'), ' ',
        'device_type:=', LaunchConfiguration('device_type'), ' ',

    ])


def declare_sagittarius_arm_robot_description_launch_arguments(
    *,
    load_gazebo_configs: Text = 'false',
    use_world_frame: Text = 'true',
    external_urdf_loc: Text = '',
    device_type: Text = 'actual',

) -> List[DeclareLaunchArgument]:
    """
    Return the `robot_description` DeclareLaunchArgument and its required children.

    DeclareLaunchArgument objects:
        - `load_gazebo_configs`
        - `use_world_frame`
        - `external_urdf_loc`

    :details: Include this in your LaunchDescription by appending its output to the list of
        DeclareLaunchArguments
    """
    return [
        DeclareLaunchArgument(
            'load_gazebo_configs',
            default_value=load_gazebo_configs,
            choices=('true', 'false'),
            description=(
                "set this to `true` if you would like to load a 'world' frame to the "
                "`robot_description` which is located exactly at the 'base_link' frame "
                'of the robot; if using multiple robots or if you would like to attach the '
                "'base_link' frame of the robot to a different frame, set this to `false`."
            ),
        ),
        DeclareLaunchArgument(
            'use_world_frame',
            default_value=use_world_frame,
            choices=('true', 'false'),
            description=(
                'if `true`, the use_world_frame is included in the `robot_description`; '
                'if `false`, the use_world_frame is not included in the `robot_description`; '
            ),
        ),
        DeclareLaunchArgument(
            'external_urdf_loc',
            default_value=TextSubstitution(text=external_urdf_loc),
            description="扩展文件名",
        ),
        DeclareLaunchArgument(
            'device_type',
            choices=(
                'actual',
                'simulation',
                'gazebo',
            ),
            default_value=device_type,
            description=(
                'configures the `robot_description` to use the actual hardware, simulation or gazebo'
            ),
        ),
        DeclareSagittariusArmDescriptionLaunchArgument(),
    ]


def determine_use_sim_time_param(
    context: LaunchContext,
    device_type_launch_arg: LaunchConfiguration
) -> Union[TextSubstitution, LaunchConfiguration]:
    """
    Set `use_sim_time` parameter to `true` if using simulated hardware.

    :param context: The launch context
    :param device_type: The `device_type` LaunchConfiguration
    :return: True if hardware is simulated, the `use_sim_time` LaunchConfiguration otherwise
    """
    if device_type_launch_arg.perform(context) in ('gazebo'):
        return TextSubstitution(text='true')
    else:
        return LaunchConfiguration('use_sim_time')
